import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const catriel = localFont({
    src: [
        { path: '../../public/fonts/catriel-regular.ttf', weight: '400', style: 'normal' },
        { path: '../../public/fonts/catriel-bold.ttf', weight: '700', style: 'normal' },
        { path: '../../public/fonts/catriel-italic.ttf', weight: '400', style: 'italic' },
        { path: '../../public/fonts/catriel-bolditalic.ttf', weight: '700', style: 'italic' },
    ],
    variable: '--font-catriel',
    display: 'swap',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${catriel.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
